# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' An Rcpp function that calculates the bootstapped Vs
#' @param  AsByK    number of bootstrap samples indexed by K
#' @param  V        left singular vectors of original sample data
#' @return A list of bootstrapped Vs indexed by Bootstrap samples
#' @export
As2Vs <- function(AsByB, V) {
    .Call(`_biostat815project_As2Vs`, AsByB, V)
}

#' An Rcpp function that carries out bootstrap PCA and calculats moment-based CIs and percentile CIs
#'
#' @param  Y    A (p x n) matrix of observed data points. 
#' @param  K   num of leading PCs of interest
#' @param  B   number of bootstrap samples
#' @param  alpha  parameter for calculating percentile CIs
#' @return A list of boostrap results
#' @export
bootPCA <- function(Y, K, B, alpha, centerSamples = 0L) {
    .Call(`_biostat815project_bootPCA`, Y, K, B, alpha, centerSamples)
}

#' An Rcpp function that calculates the bootstrap distribution of the principal components (PCs) of a low dimensional matrix.
#'
#' @param  n    A (n x n) matrix of sample scores (i.e. the product of singular values and transpose(right singular vectors) 
#' @param  DUt  transpose of UD (matrix of scores, were rows denote individuals, and columns denote measurements in the PC space.)
#' @param  K    the number of PCs to be estimated.
#' @param  B    the number of bootstrap samples   
#' @param  centerSamples  whether each bootstrap sample should be centered before calculating the SVD, 1=Yes, 0=NO(default).
#' @return A list containing left, right singular vectors and singular values of SVD(sample scores)
#' @export
bootSVD_LD <- function(n, DUt, K, B, centerSamples = 0L) {
    .Call(`_biostat815project_bootSVD_LD`, n, DUt, K, B, centerSamples)
}

#' An Rcpp function that generate bootstrapped indices
#' @param  B    number of bootstrap samples
#' @param  n    number of original sample
#' @return A (B x n) matrix  containing the bootstrapped indices
#' @export
genBootIndices <- function(B, n) {
    .Call(`_biostat815project_genBootIndices`, B, n)
}

#' An Rcpp function that calculate bootstrap percentile-based confidence intervals for the PCs of original data.
#' @param  VsByK    A list of Vs indexed by K
#' @param  B        number of bootstrap samples
#' @param  K        first K PCs of interest
#' @param  p        number of features
#' @param  alpha    (100*alpha/2, 100(1-alpha/2)) CI
#' @return A list of bootstrap percentile-based confidence intervals for the PCs.
#' @export
getHDpercentiles <- function(VsByK, B, K, p, alpha) {
    .Call(`_biostat815project_getHDpercentiles`, VsByK, B, K, p, alpha)
}

#' An Rcpp function that calculate bootstrap percentile-based confidence intervals for the PCs of sample socores.
#' @param  VsByK    A list of Vs indexed by K
#' @param  B        number of bootstrap samples
#' @param  K        first K PCs of interest
#' @param  p        number of features
#' @param  alpha    (100*alpha/2, 100(1-alpha/2)) CI
#' @return A list of bootstrap percentile-based confidence intervals for the PCs.
#' @export
getLDpercentiles <- function(AsByK, B, K, n, alpha) {
    .Call(`_biostat815project_getLDpercentiles`, AsByK, B, K, n, alpha)
}

#' An Rcpp function that calculate bootstrap moments and moment-based confidence intervals for the PCs.
#'
#' @param  AsByK  number of bootstrap samples indexed by K
#' @param  V      left singular vectors of original sample data
#' @param  B      number of bootstrap samples
#' @param  K      first K PCs of interest
#' @param  n      number of subjects 
#' @return A list of moments and moment-based CIs for the PCs
#' @export
getMomentsAndMomentCI <- function(AsByK, V, B, K, n) {
    .Call(`_biostat815project_getMomentsAndMomentCI`, AsByK, V, B, K, n)
}

#' An Rcpp function to order values in each row of the input matrix
#'
#' @param  q    number of dimension in features
#' @param  A    A matrix to be ordered
#' @param  p 
#' @param  r 
NULL

#' @return A matrix whose values in each row has ascending order
#' @export
quickSort <- function(q, A, p, r) {
    invisible(.Call(`_biostat815project_quickSort`, q, A, p, r))
}

#' An Rcpp function that Used for calculation of low dimensional standard errors & percentiles, by re-indexing the \eqn{A^b} by PC index (\eqn{k}) rather than bootstrap index (\eqn{b}).
#'
#' @param  AsByB   a size B list of matrices in the order boostrap samples
#' @param  B       number of boostrap samples
#' @param  K       first K PCs of interest
#' @return A list of reordered matrices (order by PCs)
#' @export
reindexMatricesByK <- function(AsByB, B, K) {
    .Call(`_biostat815project_reindexMatricesByK`, AsByB, B, K)
}

